# 1.Read & combine

In [43]:
import pandas as pd

In [44]:
nova_1 = pd.read_csv(r'C:\Users\muham\OneDrive\Documents\Project2_NovaMart_Streamlit\Project2_NovaMart_Streamlit\data\monthly_orders\novamart_orders_2024_01.csv')
nova_2 = pd.read_csv(r'C:\Users\muham\OneDrive\Documents\Project2_NovaMart_Streamlit\Project2_NovaMart_Streamlit\data\monthly_orders\novamart_orders_2024_02.csv')
nova_3 = pd.read_csv(r'C:\Users\muham\OneDrive\Documents\Project2_NovaMart_Streamlit\Project2_NovaMart_Streamlit\data\monthly_orders\novamart_orders_2024_03.csv')
nova_4 = pd.read_csv(r'C:\Users\muham\OneDrive\Documents\Project2_NovaMart_Streamlit\Project2_NovaMart_Streamlit\data\monthly_orders\novamart_orders_2024_04.csv')
nova_5 = pd.read_csv(r'C:\Users\muham\OneDrive\Documents\Project2_NovaMart_Streamlit\Project2_NovaMart_Streamlit\data\monthly_orders\novamart_orders_2024_05.csv')
nova_6 = pd.read_csv(r'C:\Users\muham\OneDrive\Documents\Project2_NovaMart_Streamlit\Project2_NovaMart_Streamlit\data\monthly_orders\novamart_orders_2024_06.csv')

In [45]:
pd.concat([nova_1, nova_2, nova_3, nova_4, nova_5, nova_6], ignore_index=True).to_csv(r'C:\Users\muham\OneDrive\Documents\Project2_NovaMart_Streamlit\Project2_NovaMart_Streamlit\data\monthly_orders\novamart_orders_2024.csv', index=False)

In [46]:
nova_all = pd.read_csv(r"C:\Users\muham\OneDrive\Documents\Project2_NovaMart_Streamlit\Project2_NovaMart_Streamlit\data\monthly_orders\novamart_orders_2024.csv")

In [47]:
nova_all.head()

,order_id,order_date,ship_date,customer_id,product_id,region,category,sub_category,quantity,sales,discount,profit
0,NM202401461113,2024-01-27,2024-02-01,CU0049,PR522,central,office supplies,Storage,1,$41.69,0.00,19.67
1,NM202401729507,2024-01-29,2024-01-31,CU0229,PR507,CENTRAL,Technology,Machines,4,$170.76,0.00,91.36
2,NM202401472052,2024-01-08,2024-01-13,CU0108,PR501,east,technology,Phones,1,$728.04,0.30,14.63
3,NM202401384236,2024-01-22,2024-01-27,CU0220,PR503,CENTRAL,Technology,Phones,7,$921.60,0.15,NaN
4,NM202401487969,"Jan 04, 2024","Jan 07, 2024",CU0213,PR501,SOUTH,technology,Phones,2,"$2,080.12",0.00,653.30

In [48]:
nova_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6107 entries, 0 to 6106
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      6107 non-null   object
 1   order_date    6107 non-null   object
 2   ship_date     6107 non-null   object
 3   customer_id   6107 non-null   object
 4   product_id    6107 non-null   object
 5   region        6107 non-null   object
 6   category      6107 non-null   object
 7   sub_category  6107 non-null   object
 8   quantity      6107 non-null   int64
 9   sales         6107 non-null   object
 10  discount      5864 non-null   float64
 11  profit        5925 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 572.7+ KB

In [49]:
nova_all.tail()

,order_id,order_date,ship_date,customer_id,product_id,region,category,sub_category,quantity,sales,discount,profit
6102,NM202406646031,"Jun 29, 2024","Jul 04, 2024",CU0217,PR503,central,Technology,Phones,1,$123.91,0.20,25.82
6103,NM202406675153,"Jun 28, 2024","Jul 02, 2024",CU0205,PR515,central,furniture,Bookcases,6,"$3,433.86",0.00,1533.18
6104,NM202406555464,"Jun 01, 2024","Jun 02, 2024",CU0236,PR517,SOUTH,OFFICE SUPPLIES,Binders,2,$150.35,0.15,54.63
6105,NM202406972645,"Jun 15, 2024","Jun 20, 2024",CU0158,PR503,South,technology,Phones,1,$92.93,0.40,-5.16
6106,NM202406547565,"Jun 03, 2024","Jun 04, 2024",CU0191,PR523,west,Office Supplies,Art,3,$91.85,0.40,-24.10

# 2.De-duplicate

In [50]:
nova_all.drop_duplicates()

,order_id,order_date,ship_date,customer_id,product_id,region,category,sub_category,quantity,sales,discount,profit
0,NM202401461113,2024-01-27,2024-02-01,CU0049,PR522,central,office supplies,Storage,1,$41.69,0.00,19.67
1,NM202401729507,2024-01-29,2024-01-31,CU0229,PR507,CENTRAL,Technology,Machines,4,$170.76,0.00,91.36
2,NM202401472052,2024-01-08,2024-01-13,CU0108,PR501,east,technology,Phones,1,$728.04,0.30,14.63
3,NM202401384236,2024-01-22,2024-01-27,CU0220,PR503,CENTRAL,Technology,Phones,7,$921.60,0.15,NaN
4,NM202401487969,"Jan 04, 2024","Jan 07, 2024",CU0213,PR501,SOUTH,technology,Phones,2,"$2,080.12",0.00,653.30
...,...,...,...,...,...,...,...,...,...,...,...,...
6102,NM202406646031,"Jun 29, 2024","Jul 04, 2024",CU0217,PR503,central,Technology,Phones,1,$123.91,0.20,25.82
6103,NM202406675153,"Jun 28, 2024","Jul 02, 2024",CU0205,PR515,central,furniture,Bookcases,6,"$3,433.86",0.00,1533.18
6104,NM202406555464,"Jun 01, 2024","Jun 02, 2024",CU0236,PR517,SOUTH,OFFICE SUPPLIES,Binders,2,$150.35,0.15,54.63
6105,NM202406972645,"Jun 15, 2024","Jun 20, 2024",CU0158,PR503,South,technology,Phones,1,$92.93,0.40,-5.16
6106,NM202406547565,"Jun 03, 2024","Jun 04, 2024",CU0191,PR523,west,Office Supplies,Art,3,$91.85,0.40,-24.10

# 3.Fix the sales column

In [51]:
nova_all["sales"] = nova_all["sales"].astype(str).str.replace("$", "", regex=False)
nova_all["sales"] = nova_all["sales"].str.replace(",", "", regex=False)
nova_all["sales"] = nova_all["sales"].astype(float)

In [52]:
nova_all['sales'].head()

0      41.69
1     170.76
2     728.04
3     921.60
4    2080.12
Name: sales, dtype: float64

# 4.Parse dates

In [53]:
nova_all["order_date"] = pd.to_datetime(nova_all["order_date"], format='mixed')
nova_all["ship_date"] = pd.to_datetime(nova_all["ship_date"], format='mixed')

# 5. Standardise text

In [54]:
nova_all = nova_all.rename(columns={
    "region_y": "region",
    "category_y": "category",
    "sub_category_y": "sub_category"
})

In [55]:
nova_all["category"] = nova_all["category"].str.strip().str.title()

In [56]:
nova_all["region"] = nova_all["region"].str.strip().str.title()

# 6. Handle missing values

In [57]:
nova_all["discount"] = nova_all["discount"].fillna(0)

In [58]:
nova_all["profit"] = nova_all["profit"].fillna(0)

# 7.Engineer columns: order_month, profit_margin_pct, shipping_days

In [59]:
nova_all["order_month"] = nova_all["order_date"].dt.month_name()

nova_all["shipping_days"] = (nova_all["ship_date"] - nova_all["order_date"]).dt.days

nova_all["profit_margin_pct"] = (nova_all["profit"] / nova_all["sales"]) * 100

# 8.Enrich

In [60]:
product = pd.read_csv(r"C:\Users\muham\OneDrive\Documents\Project2_NovaMart_Streamlit\Project2_NovaMart_Streamlit\data\product_lookup.csv ")

nova_all = nova_all.merge(product, on="product_id", how="left")

In [61]:
customer = pd.read_csv(r"C:\Users\muham\OneDrive\Documents\Project2_NovaMart_Streamlit\Project2_NovaMart_Streamlit\data\customer_lookup.csv")

nova_all = nova_all.merge(customer, on="customer_id", how="left")

In [62]:
nova_all = nova_all.drop(columns=[
    "region_x",
    "category_x",
    "sub_category_x"
])

# 9. Save

In [63]:
nova_all.to_csv(r"C:\Users\muham\OneDrive\Documents\Project2_NovaMart_Streamlit\Project2_NovaMart_Streamlit\data\novamart_clean.csv ", index=False)

print("Data Saved Successfully")

Data Saved Successfully